# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - run: npm ci
  
    - run: npm run build
  
    - uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: |
          dist

  ci-linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
  
    - run: npm ci

    - run: npm run lint

  ci-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci

    - run: npm run test:unit:ci

    - uses: actions/upload-artifact@v3
      with:
        name: tests-results-unit
        path: |
          *test-result.xml

  ci-e2e-firefox:
    needs: [build]
    runs-on: ubuntu-latest
    container: ${{ matrix.cypress_container.name }}

    strategy:
      matrix:
        include:
        - cypress_container: 
          name: "cypress/browsers:node16.14.0-slim-chrome99-ff97"
          firefox: 97.0.1
        - cypress_container: 
          name: "cypress/browsers:node16.5.0-chrome94-ff93"
          firefox: 93.0

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - uses: actions/download-artifact@v3
      with:
        name: build-folder
        path: ./dist
  
    - run: npm ci

    - run: npm run test:e2e:ci:firefox

    - uses: actions/upload-artifact@v3
      env:
        BROWSER_VERSION: ${{ matrix.cypress_container.firefox }}
      with:
        name: tests-results-firefox-$BROWSER_VERSION-e2e
        path: |
          *test-result.xml

  ci-e2e-chrome:
    needs: [build]
    runs-on: ubuntu-latest
    container: ${{ matrix.cypress_container.name }}

    strategy:
      matrix:
        include:
        - cypress_container: 
          name: "cypress/browsers:node16.14.0-slim-chrome99-ff97"
          chrome: 99.0.4844.51
        - cypress_container: 
          name: "cypress/browsers:node16.5.0-chrome94-ff93"
          chrome: 94.0.4606.71

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - uses: actions/download-artifact@v3
      with:
        name: build-folder
        path: ./dist

    - run: npm ci

    - run: npm run test:e2e:ci:chrome

    - uses: actions/upload-artifact@v3
      env:
        BROWSER_VERSION: ${{ matrix.cypress_container.chrome }}
      with:
        name: tests-results-chrome-$BROWSER_VERSION-e2e
        path: |
          *test-result.xml
