# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
  
    - run: npm ci
  
    - run: npm run build
  
    - uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: |
          dist

  ci-linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
  
    - run: npm ci

    - run: npm run lint

  ci-unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci

    - run: npm run test:unit:ci

    - uses: actions/upload-artifact@v3
      with:
        name: tests-results-unit
        path: |
          *test-result.xml

  ci-e2e-firefox:
    needs: [build]
    runs-on: ubuntu-latest
    container: ${{ matrix.cypress_container.name }}

    strategy:
      matrix:
        include:
        - cypress_container: "cypress/browsers:node14.17.0-chrome91-ff89"
          firefox_version: 89.0.2
        - cypress_container: "cypress/browsers:node16.5.0-chrome94-ff93"
          firefox_version: 93.0

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - uses: actions/download-artifact@v3
      with:
        name: build-folder
        path: ./dist
  
    - run: npm ci

    - run: npm run test:e2e:ci:firefox

    - uses: actions/upload-artifact@v3
      with:
        name: tests-results-firefox-${{ matrix.firefox_version }}-e2e
        path: |
          *test-result.xml

  ci-e2e-chrome:
    needs: [build]
    runs-on: ubuntu-latest
    container: ${{ matrix.cypress_container }}

    strategy:
      matrix:
        include:
        - cypress_container: "cypress/browsers:node14.17.0-chrome91-ff89"
          chrome_version: 91.0.4472.114
        - cypress_container: "cypress/browsers:node16.5.0-chrome94-ff93"
          chrome_version: 94.0.4606.71

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - uses: actions/download-artifact@v3
      with:
        name: build-folder
        path: ./dist

    - run: npm ci

    - run: npm run test:e2e:ci:chrome

    - uses: actions/upload-artifact@v3
      with:
        name: tests-results-chrome-${{ matrix.chrome_version }}-e2e
        path: |
          *test-result.xml
